#ifndef SAMPLERS_SH_HEADER_GUARD
#define SAMPLERS_SH_HEADER_GUARD

#define SAMPLER_PBR_BASECOLOR      0
#define SAMPLER_PBR_METALROUGHNESS 1
#define SAMPLER_PBR_NORMAL         2

#define SAMPLER_LIGHTS_POINTLIGHT_POSITION 3
#define SAMPLER_LIGHTS_POINTLIGHT_POWER    4

#define SAMPLER_CLUSTERS_CLUSTERS 5
#define SAMPLER_CLUSTERS_LIGHTINDICES 6
#define SAMPLER_CLUSTERS_LIGHTGRID 7
#define SAMPLER_CLUSTERS_ATOMICINDEX 8

#endif // SAMPLERS_SH_HEADER_GUARD
