#ifndef SAMPLERS_SH_HEADER_GUARD
#define SAMPLERS_SH_HEADER_GUARD

// shared

#define SAMPLER_PBR_BASECOLOR 0
#define SAMPLER_PBR_METALROUGHNESS 1
#define SAMPLER_PBR_NORMAL 2

#define SAMPLER_LIGHTS_POINTLIGHTS 3

// per renderer

#define SAMPLER_CLUSTERS_CLUSTERS 4
#define SAMPLER_CLUSTERS_LIGHTINDICES 5
#define SAMPLER_CLUSTERS_LIGHTGRID 6
#define SAMPLER_CLUSTERS_ATOMICINDEX 7

#define SAMPLER_DEFERRED_DIFFUSE_A 4
#define SAMPLER_DEFERRED_NORMAL 5
#define SAMPLER_DEFERRED_F0_METALLIC 6
#define SAMPLER_DEFERRED_DEPTH 7

#endif // SAMPLERS_SH_HEADER_GUARD
